/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmeRouteImport } from './routes/sme'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SmeStatusRouteImport } from './routes/sme.status'
import { Route as SmeApplyRouteImport } from './routes/sme.apply'

const SmeRoute = SmeRouteImport.update({
  id: '/sme',
  path: '/sme',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmeStatusRoute = SmeStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => SmeRoute,
} as any)
const SmeApplyRoute = SmeApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => SmeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sme': typeof SmeRouteWithChildren
  '/sme/apply': typeof SmeApplyRoute
  '/sme/status': typeof SmeStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sme': typeof SmeRouteWithChildren
  '/sme/apply': typeof SmeApplyRoute
  '/sme/status': typeof SmeStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sme': typeof SmeRouteWithChildren
  '/sme/apply': typeof SmeApplyRoute
  '/sme/status': typeof SmeStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sme' | '/sme/apply' | '/sme/status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sme' | '/sme/apply' | '/sme/status'
  id: '__root__' | '/' | '/sme' | '/sme/apply' | '/sme/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SmeRoute: typeof SmeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sme': {
      id: '/sme'
      path: '/sme'
      fullPath: '/sme'
      preLoaderRoute: typeof SmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sme/status': {
      id: '/sme/status'
      path: '/status'
      fullPath: '/sme/status'
      preLoaderRoute: typeof SmeStatusRouteImport
      parentRoute: typeof SmeRoute
    }
    '/sme/apply': {
      id: '/sme/apply'
      path: '/apply'
      fullPath: '/sme/apply'
      preLoaderRoute: typeof SmeApplyRouteImport
      parentRoute: typeof SmeRoute
    }
  }
}

interface SmeRouteChildren {
  SmeApplyRoute: typeof SmeApplyRoute
  SmeStatusRoute: typeof SmeStatusRoute
}

const SmeRouteChildren: SmeRouteChildren = {
  SmeApplyRoute: SmeApplyRoute,
  SmeStatusRoute: SmeStatusRoute,
}

const SmeRouteWithChildren = SmeRoute._addFileChildren(SmeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SmeRoute: SmeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
